### ISSUE TITLE
Agreggate function (size) not working properly after filter is applied.

### ISSUE THREAD

**Issue by lakshan93** [json-path/JsonPath#357] opened 2017-06-07 06:26 UTC
There are list of objects
{
  "list": [
    {
      "value": 1,
      "present": "yes"
    },
    {
      "value": 2,
      "present": "no"
    },
    {
      "value": 3,
      "present": "yes"
    }
  ]
}

The path $.list[?(@.present == 'yes')].value.size() gives me wrong result.
Expected: 2
Actual: [null, null]

Looks like rather it calculate the size of the list, it calculate individuals elements inside list and since there is no string processing, it is returning null for each element, which is not expected.

**Comment by jochenberger** [comment] 2017-06-29 14:38
More or less a duplicate of #272

**Comment by kallestenflo** [comment] 2017-06-30 07:36
Duplicate (or related to) #272

**Closed by kallestenflo** 2017-06-30 07:36 UTC
